[package]
name = "ddmadm"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21", features = ["full"] }
structopt = "0.3"
anyhow = "1"
slog = "2.7"
slog-term = "2.7"
slog-async = "2.7"
slog-envlogger = "2.2"
ddm = { path = "../ddm" }
ddm-admin-client = { path = "../ddm-admin-client" }
