[workspace]

members = [
    "lab",
    "icmpv6",
    "ddm",
    "ddm2",
    "ddmadm",
    "ddm-admin-client",
    "ddm-local",
    "ddm-apigen",
    "ddm-illumos",
    "console",
    "package",
    "util",
]
