[package.mg-ddm]
rust.binary_names = ["ddm-illumos", "ddmadm"]
rust.release = true
service_name = "mg-ddm"
zone = true
[[package.mg-ddm.paths]]
from = "smf/ddm"
to = "/var/svc/manifest/site/mg-ddm"
[[package.mg-ddm.paths]]
from = "smf/ddm_method_script.sh"
to = "/opt/oxide/mg-ddm/bin/ddm_method_script.sh"
