[package.maghemite]
rust.binary_names = ["ddm-illumos", "ddmadm"]
rust.release = true
service_name = "maghemite"
zone = true
[[package.maghemite.paths]]
from = "smf/ddm"
to = "/var/svc/manifest/site/mg-ddm"
[[package.maghemite.paths]]
from = "smf/ddm_method_script.sh"
to = "/opt/oxide/maghemite/bin/ddm_method_script.sh"
