[package]
name = "ddm"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.14", features = ["full"] }
anyhow = "1"
slog = "2.7"
slog-term = "2.7"
slog-async = "2.7"
slog-envlogger = "2.2"
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
schemars = { version = "0.8.0", features = [ "uuid" ] }
serde = "1.0"
serde_json = "1.0"
hyper = { version = "0.14", features = ["full"] }
thiserror = "1.0"
rand = "0.8"
rand_distr = "0.4"
netadm-sys = { path = "/home/ry/src/netadm-sys/lib" }
#netadm-sys = { git = "ssh://git@github.com/oxidecomputer/netadm-sys", branch = "routing" }
socket2 = { version = "0.4", features = ["all"] }
icmpv6 = { path = "../icmpv6" }
async-trait = "0.1.52"
hostname = "0.3"
structopt = "0.3"

[[bin]]
name = "ddm-illumos"
path = "src/illumos/main.rs"

[[bin]]
name = "ddm-local"
path = "src/local/main.rs"
