[package]
name = "ddm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1.14", features = ["full", "tracing"] }
slog = "2.7"
slog-term = "2.7"
slog-async = "2.7"
slog-envlogger = "2.2"
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
schemars = { version = "0.8.0", features = [ "uuid" ] }
serde = "1.0"
serde_json = "1.0"
hyper = { version = "0.14", features = ["full"] }
thiserror = "1.0"
libnet = { git = "https://github.com/oxidecomputer/netadm-sys" }
socket2 = { version = "0.4", features = ["all"] }
icmpv6 = { path = "../icmpv6" }
async-trait = "0.1.52"
hostname = "0.3"
protod-api = { git = "https://github.com/oxidecomputer/dendrite" }

[dependencies.dendrite-common]
git = "https://github.com/oxidecomputer/dendrite"
package = "common"
