[package]
name = "riftadm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.0.0-beta.4", features = ["color"] }
reqwest = "0.11"
rift = { path = "../rift" }
platform = { path = "../platform" }
tabwriter = { version = "1", features = ["ansi_formatting"] }
colored = "2"
